---
- hosts: gw01n01
  tasks:
      #    - name: Https
      #apt: name=apt-transport-https state=installed 
      #- name: main
      #apt_repository: repo='deb http://debian.netcologne.de/debian buster main' state=present
      

      #    - name: Add Repositories
      #apt_repository: repo='deb https://repo.universe-factory.net/debian/ sid main' state=present

    #- name: Add buster backports
    #  apt_repository: repo="deb http://debian.mirrors.ovh.net/debian/ buster-backports main" state=present
    - name: Add buster-backports repo
      apt_repository: repo="deb http://deb.debian.org/debian/ buster-backports main" state=present filename=buster-backports

    - lineinfile: 
        dest: /etc/apt/preferences.d/limit-buster-backports
        line: "Package: *" 
        create: yes
    - lineinfile: 
        dest: /etc/apt/preferences.d/limit-buster-backports 
        line: "Pin: release n=buster-backports"
    - lineinfile: 
        dest: /etc/apt/preferences.d/limit-buster-backports 
        line: "Pin-Priority: 90"

    - name: Install all required packages
      apt: name={{item}} state=present update_cache=false
      with_items:
          - rsync
          - bsd-mailx
          - apt-transport-https
          - postfix
          - mutt
          - collectd-core
          - locales
          - nginx
          - host
          - psmisc
          - fastd
          - isc-dhcp-relay
          - tinc
          - linux-headers-amd64
          - htop
          - libsodium-dev
          - libuecc-dev
          - libjson-c-dev
          - bison
          - cmake
          - mtr
          - vim
          - iftop 
          - uthash-dev
          - mosh
          - apt-transport-https
          - equivs
          - unbound
          - bird
          - bridge-utils
          - ethtool
          - git
            #- iproute
          - iptables
          - iptables-persistent
          - man-db
          - ntp
          - python3
          - radvd
          - rrdtool
          - sysfsutils
          - vnstat
          - vnstati
          - libcap-dev
          - pkgconf
          - libgps-dev
          - strace
          - python3-venv

            #    - name: Install netaddr using pip
            # pip: name=netaddr
