---
- hosts: gws
  tasks:
    - name: pull FfsConfigGenerator from github
      git: repo=https://github.com/freifunk-stuttgart/FfsConfigGenerator.git dest=/root/ConfigGenerator update=yes version=develop

    - name: Execute config generator
      command: ./gen_config.py --gwnum 1 --instance 3
      args:
        chdir: /root/ConfigGenerator

    - name: Copy over config files
      command: cp -r /root/ConfigGenerator/etc /
